# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-27 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0004_kategorie_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ECHO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('echo_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LUS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lus_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='link',
            name='kategorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='kompendium.Kategorie'),
        ),
    ]
