# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0005_auto_20161127_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilderliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liste_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Unterart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unterart_text', models.CharField(max_length=200)),
                ('unterart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompendium.Art')),
            ],
        ),
        migrations.DeleteModel(
            name='ECHO',
        ),
        migrations.DeleteModel(
            name='LUS',
        ),
        migrations.AddField(
            model_name='bilderliste',
            name='liste_art',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompendium.Unterart'),
        ),
    ]
