# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0006_auto_20161128_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='US_Bilderliste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bilderliste_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='US_Selektion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selektion_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='bilderliste',
            name='liste_art',
        ),
        migrations.RemoveField(
            model_name='unterart',
            name='unterart',
        ),
        migrations.DeleteModel(
            name='Art',
        ),
        migrations.DeleteModel(
            name='Bilderliste',
        ),
        migrations.DeleteModel(
            name='Unterart',
        ),
        migrations.AddField(
            model_name='us_bilderliste',
            name='bilderliste_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kompendium.US_Selektion'),
        ),
    ]
