# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0007_auto_20161128_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natrium', models.IntegerField()),
                ('kalium', models.IntegerField()),
            ],
        ),
    ]
