# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-14 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0013_auto_20161214_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='heading_2',
            field=models.CharField(blank=True, default='Epidemiologie', max_length=200, null=True),
        ),
    ]
