# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-17 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0015_entry_image1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
