# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0016_auto_20161217_1409'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('news_text', models.CharField(blank=True, max_length=200, null=True)),
                ('news_image', models.ImageField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
