# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0017_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
