# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-03 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0019_auto_20161221_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='EDIC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
