# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-09 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0020_edic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='rechner',
            name='alter',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Age'),
        ),
        migrations.AddField(
            model_name='rechner',
            name='blutzucker',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Glucose'),
        ),
        migrations.AddField(
            model_name='rechner',
            name='bun',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='BUN'),
        ),
        migrations.AddField(
            model_name='rechner',
            name='geschlecht',
            field=models.BooleanField(choices=[(True, 'male'), (False, 'female')], default=True, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='rechner',
            name='kg',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='kg'),
        ),
        migrations.AddField(
            model_name='rechner',
            name='serumOsmo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='S-Osmo'),
        ),
        migrations.AddField(
            model_name='rechner',
            name='unatrium',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='U-Na+'),
        ),
        migrations.AddField(
            model_name='rechner',
            name='uosmo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='U-Osmo'),
        ),
        migrations.AlterField(
            model_name='rechner',
            name='kalium',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='K+'),
        ),
        migrations.AlterField(
            model_name='rechner',
            name='natrium',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Na+'),
        ),
    ]
