# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-11 20:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0021_auto_20170709_2224'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calcs',
        ),
    ]
