# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-03-29 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0024_auto_20180314_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='bga',
            name='serumOsmo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='S-Osmo'),
        ),
        migrations.AddField(
            model_name='bga',
            name='uosmo',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='U-Osmo'),
        ),
        migrations.AlterField(
            model_name='bga',
            name='chloride',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Cl-'),
        ),
        migrations.AlterField(
            model_name='bga',
            name='lactate',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Laktat'),
        ),
        migrations.AlterField(
            model_name='bga',
            name='ph',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='pH'),
        ),
        migrations.AlterField(
            model_name='bga',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='K+'),
        ),
        migrations.AlterField(
            model_name='bga',
            name='sodium',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Na+'),
        ),
    ]
