# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-30 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kompendium', '0026_auto_20180329_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bga',
            name='blutzucker',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Glucose'),
        ),
        migrations.AlterField(
            model_name='bga',
            name='bun',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='BUN'),
        ),
    ]
